# Get All
GET http://localhost:4000/api/hubs


###

# Get Hub by ID
GET http://localhost:4000/api/hubs/1

###
POST http://localhost:4000/api/hubs
Content-Type: "application/json"

{
  "name": "api-3"
}

###

# Get All Messages
GET http://localhost:4000/api/hubs/1/messages

###

// Add message
POST http://localhost:4000/api/hubs/1/messages
Content-Type: "application/json"

{
  "text": "do you have a hubId column?",
	"sender": "Me",
	"hub_id": 1
}

